login:
  oauth2_enabled:
    default: false
    client: true
  oauth2_client_id: ""
  oauth2_client_secret: ""
  oauth2_authorize_url: "https://apis.roblox.com/oauth/v1/authorize"
  oauth2_authorize_signup_url: ""
  oauth2_token_url: "https://apis.roblox.com/oauth/v1/token"
  oauth2_token_url_method:
    default: "POST"
    type: enum
    choices:
      - GET
      - POST
  oauth2_callback_user_id_path: ""
  oauth2_callback_user_info_paths:
    type: list
    default: ""
  oauth2_fetch_user_details:
    default: true
    validator: "Oauth2FetchUserDetailsValidator"
  oauth2_user_json_url: "https://apis.roblox.com/oauth/v1/userinfo"
  oauth2_user_json_url_method:
    default: "GET"
    type: enum
    choices:
      - GET
      - POST
  oauth2_json_user_id_path: "sub"
  oauth2_json_username_path: "preferred_username"
  oauth2_json_name_path: "nickname"
  oauth2_json_email_path: ""
  oauth2_json_email_verified_path: ""
  oauth2_json_avatar_path: ""
  oauth2_email_verified: false
  oauth2_overrides_email: false
  oauth2_overrides_name: true
  oauth2_overrides_username: true
  oauth2_overrides_avatar: true
  oauth2_send_auth_header: true
  oauth2_send_auth_body: false
  oauth2_debug_auth: false
  oauth2_authorize_options:
    default: "scope"
    type: list
  oauth2_scope: "openid profile"
  oauth2_button_title:
    default: "ROBLOX"
    client: true
  oauth2_allow_association_change:
    default: false
  oauth2_disable_csrf:
    default: false
    hidden: true
